namespace PF2
{
    enum SkillActionType
    {
        //GeneralActions
        DecipherWriting,
        EarnIncome,
        IdentifyMagic,
        LearnASpell,
        RecallKnowledge,
        Subsist,
        //Acrobatics
        Balance,
        TumbleThrough,
        ManeuverInFlight,
        Squeeze,
        //Arcana
        BorrowAnArcaneSpell,
        //Athletics
        Climb,
        ForceOpen,
        Grapple,
        HighJump,
        LongJump,
        Shove,
        Swim,
        Trip,
        Disarm,
        //Crafting
        Repair,
        Craft,
        IdentifyAlchemy,
        //Deception
        CreateADiversion,
        Impersonate,
        Lie,
        Feint,
        //Diplomacy
        GatherInformation,
        MakeAnImpression,
        Request,
        //Intimidation
        Coerce,
        Demoralize,
        //Lore
        //EarnIncome
        //Medicine
        AdministerFirstAid,
        TreatDisease,
        TreatPoison,
        TreatWounds,
        //Nature
        CommandAnAnimal,
        //Occultism
        //Performance
        Perform,
        //Religion
        //Society
        CreateForgery,
        //Stealth
        ConcealAnObject,
        Hide,
        Sneak,
        //Survival
        SenseDirection,
        CoverTracks,
        Track,
        //Thievery
        PalmAnObject,
        Steal,
        DisableADevice,
        PickALock
    }
}